# Generated by Django 6.0.3 on 2026-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_measurement_id_alter_measurement_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='id',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
